#!/bin/bash

#  _____ _   _  ___  ____       _____ _                        _ _
# |_   _| | | |/ _ \|  _ \     |  ___(_)_ __ _____      ____ _| | |
#   | | | |_| | | | | |_) |____| |_  | | '__/ _ \ \ /\ / / _` | | |
#   | | |  _  | |_| |  _ <_____|  _| | | | |  __/\ V  V / (_| | | |
#   |_| |_| |_|\___/|_| \_\    |_|   |_|_|  \___| \_/\_/ \__,_|_|_|
#
# iptables loader
# License: MIT (X11) License
# Copyright: 2015-2021 Andi Dittrich, 2016-2021 Aenon Dynamics
# https://github.com/AenonDynamics/thor-firewall
#

_VERSION="1.0.1"
_LICENSE="MPL-2.0"
_REPOSITORY="https://github.com/AenonDynamics/thor-firewall"

show_usage(){
    cat << EOF
Usage: thor-firewall <command> [args...]

Options:
    -h,--help               Displays this help
    -v,--version            Displays version

Commands:
    start                   Initialize firewall rules/tables/chains
    stop                    Flush all iptables chains/rules
    restart                 Reload/Initialize firewall rules/tables/chains
    open                    WARNING: Dropping all Firewall+NAT Rules and set system to ACCEPT ALL
    status                  Show all configures rules/tables/chains

EOF
    exit 0
}

show_version(){
    cat << EOF
thor-firewall » v${_VERSION} » iptables loader
License: ${_LICENSE} https://opensource.org/licenses/${_LICENSE}
Repository: ${_REPOSITORY}
EOF
    exit 0
}

# simple processing for help+versioning commands
[ "$1" = "--help" ] || [ "$1" = "-h" ] || [ -z "$1" ] && show_usage
[ "$1" = "--version" ] || [ "$1" = "-v" ] && show_version

# fail on error
set -e

# Config directory (debian, ubuntu)
CONF_DIR="/etc/thor-firewall"

# load bash functions lib
source /usr/share/thor-firewall/bash-functions

# config exist ?
[ ! -f "$CONF_DIR/thor.conf" ] && panic "ERROR: thor.conf doesn't exist"

# load config
source "$CONF_DIR/thor.conf"

# https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/networking/ip-sysctl.txt
sysctl_tweaks_ip4(){
    # Enable source validation by reversed path, as specified in RFC1812, RFC3704 Strict Reverse Path
    echo 1 > /proc/sys/net/ipv4/conf/all/rp_filter
    echo 1 > /proc/sys/net/ipv4/conf/default/rp_filter

    # Do not accept source routing RFC791
    echo 0 > /proc/sys/net/ipv4/conf/all/accept_source_route
    echo 0 > /proc/sys/net/ipv4/conf/default/accept_source_route

    # Do not send ICMP Redirects ony any Interface
    echo 0 > /proc/sys/net/ipv4/conf/all/send_redirects
    echo 0 > /proc/sys/net/ipv4/conf/default/send_redirects

    # Do not accept ICMP Redirects on any Interface
    echo 0 > /proc/sys/net/ipv4/conf/all/accept_redirects
    echo 0 > /proc/sys/net/ipv4/conf/default/accept_redirects

    # Do not accept secure ICMP Redirects on any Interface
    echo 0 > /proc/sys/net/ipv4/conf/all/secure_redirects
    echo 0 > /proc/sys/net/ipv4/conf/default/secure_redirects

    # Disable System Request debugging functionality of the kernel
    echo 0 > /proc/sys/kernel/sysrq

    # Ignore all ICMP ECHO and TIMESTAMP requests sent to it via broadcast/multicast
    echo 1 > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts

    # ICMP "bad error messages" protection
    echo 1 > /proc/sys/net/ipv4/icmp_ignore_bogus_error_responses

    # Prevent against the common 'syn flood attack'
    echo 1 > /proc/sys/net/ipv4/tcp_syncookies
    echo 2 > /proc/sys/net/ipv4/tcp_synack_retries

    # Do NOT log martians - rejected by iptables
    echo 0 > /proc/sys/net/ipv4/conf/all/log_martians
    echo 0 > /proc/sys/net/ipv4/conf/default/log_martians

    # ICMP Rate limiting to 200/s
    echo 2 > /proc/sys/net/ipv4/icmp_ratelimit

    # tcp fin timeout to 30
    echo 30 > /proc/sys/net/ipv4/tcp_fin_timeout
}

# Startup Checks
# ---------------------------------------
fw_startup_check(){
    # check for iptables
    if [ ! -x $IPT ]; then
        panic "ERROR: iptables command not found"
    fi

    # check for ipset (not empty, bin available)
    if [ ! -z $IPS ] && [ ! -x $IPS ]; then
        panic "ERROR: ipset command not found"
    fi

    # check for root user
    USER_ID="$(id -u)"
    if [ ! $USER_ID -eq 0 ]; then
        panic "ERROR: please run this script as root"
    fi
}

# Flush all rules
# ---------------------------------------
fw_flush(){
    # Flush all rules
    $IPT -t filter -F
    $IPT -t nat -F
    $IPT -t mangle -F
    $IPT -t raw -F

    # Delete all custom chains
    $IPT -t filter -X
    $IPT -t nat -X
    $IPT -t mangle -X
    $IPT -t raw -X

    # Flush all IP-sets
    if [ ! -z $IPS ]; then
        $IPS destroy
    fi
}

# Router or Host Mode ? Select ip4/ip6
# ---------------------------------------
fw_operation_mode(){
    # router or host mode ?
    if [ "$CONF_OPERATION_MODE" = "router" ]; then
        # enable routing
        echo 1 > /proc/sys/net/ipv4/ip_forward
    else
        # disable routing
        echo 0 > /proc/sys/net/ipv4/ip_forward
    fi

    # ip6 supported ? may missing on wrt firmware
    if [ -d "/proc/sys/net/ipv6" ]; then
        # ipv4 only ?
        if [ "$CONF_PROTOCOLS" = "ip6" ]; then
            # enable ipv6
            echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6
            echo 0 > /proc/sys/net/ipv6/conf/default/disable_ipv6
        else
            # disable ipv6
            echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
            echo 1 > /proc/sys/net/ipv6/conf/default/disable_ipv6
        fi
    fi
   
}

# Flush all rules and set state to ALLOW ALL
# ---------------------------------------
fw_open(){
    # Flush all rules
    fw_flush

    # Accept all packages (default policy on no match)
    $IPT -t filter -P INPUT ACCEPT
    $IPT -t filter -P FORWARD ACCEPT
    $IPT -t filter -P OUTPUT ACCEPT
}

# Display the firewall status
# ---------------------------------------
fw_status(){
    # Show Filter Table (Rules)
    print_heading "Firewall Rules"
    $IPT -t filter -n -L -v --line-numbers

    # Show NAT Table
    print_heading "NAT Table";
    $IPT -t nat -n -L -v --line-numbers

    # Show RAW Table
    print_heading "RAW Table";
    $IPT -t raw -n -L -v --line-numbers

    # Show Mangle Table
    print_heading "MANGLE Table";
    $IPT -t mangle -n -L -v --line-numbers
}

# Load Ruleset (single file)
# ---------------------------------------
fw_load_rule_file(){
    log_info "processing file [$1]"

    # counter
    NUM_RULES=0

    # Firewall Rules (external lists)
    if [ -f "$1" ]; then
        IFS=' '
        while read ruleset
        do
            # valid line ?
            if [ ! -z "$ruleset" ]; then
                # apply rule
                $IPT $ruleset && {
                    # increment on success
                    NUM_RULES=$((NUM_RULES+1))
                } || {
                    log_error "ERROR: cannot load rule. skipping.. $ruleset"
                }
            fi
        done < "$1"

        log_success "rules loaded: $NUM_RULES"
    else
        log_error "ERROR: file [$1] doesn't exist"
    fi
}

# Load Ruleset (multiple files)
# ---------------------------------------
fw_load_rules_bulk(){
    # Firewall Rules (external lists)
    if [ ! -d "$1" ]; then
        log_error "ERROR: [$1] doesn't exist/not a directory"
        return 1
    fi
    
    # get all *.conf file with leading priority "00-"
    find $1 -type f,l | grep -E '/[0-9]+-.*\.conf$' | sort | while read -r file
    do
        # load ruleset
        fw_load_rule_file $file
    done
}

# Startup (Init)
# Flush all rules and set state to BLOCK ALL
# ---------------------------------------
fw_startup(){
    print_subheading "initializing thor-firewall"
    
    # check user, binaries
    fw_startup_check

    # Select Operation Mode
    fw_operation_mode

    # Apply Tweaks
    sysctl_tweaks_ip4

     # Flush all rules
    fw_flush

    # Drop all packages (default policy on no match)
    $IPT -t filter -P INPUT DROP
    $IPT -t filter -P FORWARD DROP
    $IPT -t filter -P OUTPUT DROP

    # apply firewall rules
    # legacy config file exist ?
    if [ -f "$CONF_DIR/fw_rules.conf" ]; then
        log_info "using legacy configuration file"
        fw_load_rule_file $CONF_DIR/fw_rules.conf
    else
        log_info "using configuration fileset in $CONF_DIR/rules.ip4.d"
        fw_load_rules_bulk $CONF_DIR/rules.ip4.d
    fi

    # READY STATE
    print_heading "rulesets applied - SYSTEM ONLINE"
}

# Command Dispatching
# ---------------------------------------
case "$1" in
    # general start/stop/restart actions
    start)
        fw_startup
        exit 0
    ;;

    stop)
        fw_flush
        exit 0
    ;;

    restart)
        fw_startup
        exit 0
    ;;

    # Allow All
    open)
        print_heading "WARNING: Dropping all Firewall+NAT Rules and set system to ACCEPT ALL"
        fw_open
        exit 0
    ;;

    status)
        fw_status
        exit 0
    ;;

    *)
        show_usage
        exit 1
    ;;
esac
